server:
  port: 8000
spring:
  application:
    name: server-auth
logging:
  level:
    root: INFO
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE
    com.itmuch.youran.persistence: ERROR
eureka:
  client:
    serviceUrl:
      defaultZone: http://vap:123456@localhost:8761/eureka/
  instance:
    preferIpAddress: true
